version: "3.9"

services:
  bank-app:
    image: springboot-bank
    container_name: bank-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - bank-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assesment_bank?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: assesment_bank
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - bank-net

networks:
  bank-net:
